services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
  - type: web
    name: keep-alive
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python keep_alive.py
    plan: free
